swagger: "2.0"
info:
  description: "SynergyCP RWhois Package API documentation"
  version: "1.0.0"
  title: "SynergyCP RWhois Package"
host: "api.yoursynergycp.com"
basePath: "/pkg/rwhois/"
schemes:
- "http"
- "https"
paths:
  /ptr:
    post:
      summary: "Create a new Contact Record, or overwrite an existing one"
      description: ""
      operationId: "addContact"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        description: "The Contact Record that needs to be added to the DNS server"
        schema:
          $ref: "#/definitions/Contact"
      responses:
        400:
          description: "Invalid input"
      security: 
      - api_key: []
    get:
      summary: "List all Contact Records"
      description: ""
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "entity"
        description: "(Optional) The ID of the IP entity you wish to lookup records for"
        type: "integer"
        format: "int64"
      - in: "query"
        name: "q"
        description: "(Optional) Text-based search of the Contact and IP records"
        type: "string"
      responses:
        400:
          description: "Invalid input"
      security: 
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
definitions:
  Contact:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
      ptr:
        type: "string"
        example: "some.hostname"
        description: "The hostname that the Contact record should point to"
      ip:
        type: "string"
        example: "1.1.1.1"
        description: "The IP address that needs to point to the Contact record"
